apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxyless-client.fullname" . }}
  labels:
    {{- include "proxyless-client.labels" . | nindent 4 }}
data:
  PROXYLESS_SERVER_ADDR: {{ .Values.app.proxylessServerAddresses | quote }}
