apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxyless-client.fullname" . }}
  labels:
    {{- include "proxyless-client.labels" . | nindent 4 }}
data:
  XDS_SERVER_TARGET: "xds:///proxyless-server:9090"
  HEALTH_CHECK_SERVER_LISTEN_ADDR: ":9091"
