apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxyless-server.fullname" . }}
  labels:
    {{- include "proxyless-server.labels" . | nindent 4 }}
data:
  XDS_SERVER_LISTEN_ADDR: ":9090"
